### ISSUE TITLE
Run in Browser. No Node

### ISSUE THREAD

**Issue by sysmaya** [fontello/svgpath#63]
Since I use this script on a "normal web", not node js. ??
It's a small svg editor, which runs 100% in the client's browser.
Something like..
<script type="module" src="svgpath-master/lib/svgpath.js"></script>
But that obviously doesn't work

**Comment by dtgreene** [comment]
I think the only thing stopping you from running in a browser is the `commonjs` format since there are no external dependencies. Here's a couple of things that could work:

- Use a web bundler like WebPack, Vite, esbuild, etc. 
- Fork the repo and convert the files to ES modules 
- Manually merge all the source files into a single file

**Comment by sysmaya** [comment]
This library is very important, and with few or no alternatives.
So using Browserify, I've created an option that runs 100% in the browser.

[https://github.com/sysmaya/svgpath-browserify](https://github.com/sysmaya/svgpath-browserify)
